### PR TITLE
refactor: monodeploy as monorepo

### PR DESCRIPTION
**Pull request by noahnu**
## Description

TODO

### CODE REVIEW

**Comment by mcataford** [comment]
Prepped `monodeploy-cli`, `monodeploy-changelog` and `monodeploy-logging`. For the first, dependencies weren't set up in `package` back to `monodeploy`, for the others, I moved over the relevant files, adjusted the dependencies and made sure that test/lint/build passes locally.

Few kinks:
- I'm not sure if it's because we're using workspaces v. published packages, but some devDependencies `build` depends on (types) needed to be installed in the relevant workspace's `package`. Not sure if it's a workspaces thing.
- I introduced some duplication at the `utils` level. We might want to create a common `sharedUtils`-type workspace that just contains the utils that are used by multiple core use cases to avoid duplicating them across workspaces. Up to discussion.
- Similarly, I'm not sure where types belong. We could split types off in cases where they are only relevant to one workspace (i.e. changeset-related types could live in `monodeploy-changelog`. Uncertain of the best course of action here.
- Added a line in CI to address current CI failures; because of workspaces, cross-workspace imports will expect the `lib` to be resolved, which only works once `build` has run at the toplevel workspace, generating libs for each workspace. Not sure if there's a workspace trick there, but in the meantime, doing `yarn build && yarn lint:ci` works fine locally.

**Comment by mcataford** [comment]
Will check back in tomorrow, and will have time later on Saturday + Sunday to pitch in some more.

**Comment by noahnu** [comment]
Splitting off types when it's only relevant to one workspace makes sense to me.

Regarding CI, let's just start with a build.

**Comment by mcataford** [comment]
Addressed the CI point, builds should be passing now so it'll be good north start for the rest of the work on this branch. :star:

**Pull request merged**
